# -*- coding: utf-8 -*-
"""1-topshiriq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiaojbUTnCZIpZN7XQnha_taYYe9YKdS
"""

import matplotlib.pyplot as plt
import numpy as np

# Sinus funksiyasining grafikini chizish
x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure(figsize=(10, 4))

# Grafik 1: Sinus funksiyasi
plt.subplot(1, 2, 1)
plt.plot(x, y, label='Sinus(x)', color='blue')
plt.title('Sinus Funksiyasining Grafik')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.grid(True)
plt.legend()

# Tasodifiy nuqtalar uchun scatter grafik
x_scatter = np.random.uniform(0, 10, 50)
y_scatter = np.random.uniform(0, 10, 50)

plt.subplot(1, 2, 2)
plt.scatter(x_scatter, y_scatter, color='blue', label='Nuqtalar')
plt.title('Tasodifiy Nuqtalar Scatter Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.grid(True)
plt.legend()

# Grafiklarni ko'rsatish
plt.tight_layout()
plt.show()