# -*- coding: utf-8 -*-
"""2topshiriq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kD_r_lbQJ2Ms7rG_TWQXe7JFAdnz3vyw
"""

import pandas as pd

# GitHub URL-dan ma'lumotlarni yuklab olish
url = "https://raw.githubusercontent.com/Zulayho06/Maxsus-topshiriq/main/WHO%20COVID-19%20cases.csv"

# CSV faylni pandas DataFrame'ga yuklash
df = pd.read_csv(url)

# Har bir davlatdagi umumiy COVID holatlarining sonini hisoblash
country_cases = df.groupby('Country')['New_cases'].sum()

# Natijani chop etish
print("Davlatlar bo'yicha COVID holatlari:")
print(country_cases)

# Eng ko'p holat aniqlangan 10 davlatni ko'rsatish
top_10_countries = country_cases.sort_values(ascending=False).head(10)
print("\nEng ko'p holat aniqlangan 10 davlat:")
print(top_10_countries)

# Natijani grafikda ko'rsatish
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
top_10_countries.plot(kind='bar', color='skyblue')
plt.title('Eng ko\'p COVID holatlari aniqlangan davlatlar')
plt.xlabel('Davlat')
plt.ylabel('COVID holatlarining soni')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()